services:
  nginx:
    container_name: nginx
    build: Nginx/
    ports:
      - "8080:80"
      - "8443:443"
    restart: always
    networks:
      - app
    depends_on:
      - back
      - front

  back:
    container_name: back
    build: Back/
    env_file: .env
    restart: always
    ports: 
      - "3000:3000"
    volumes:
      - ./Back:/usr/src/app
    depends_on:
      - db
    networks:
      - app

  front:
    container_name: front
    build: Front/
    env_file: .env
    restart: always
    ports: 
      - "5173:5173"
    volumes:
      - ./Front:/usr/src/app
    networks:
        - app

  db:
    image: postgres:15
    container_name: db
    env_file: .env
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./Data:/var/lib/postgresql
    networks:
      - app


networks:
  app:
    driver: bridge

# volumes:
#   back:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '${PWD}/Back'
#   front:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '${PWD}/Front'
#   db:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '${PWD}/Data'